// Runtime validator for the scene schema (TODO.md Phase E). The schema
// itself is TypeScript-typed, but authored `Video` data (hand-written, or
// generated by another agent) is `unknown` until something actually checks
// it — that is the point of this file: a bad scene fails loudly, with a
// precise `path`, at author time, instead of quietly rendering a blank or
// broken frame. `sceneSteps`/`sceneDuration` (../timing.ts) assume the data
// they're handed is already well-formed; this is what gets to assume that.

import {
  isRecord, isString,
  pushError,
  optionalString, optionalEnum,
} from "./validate.helpers";
import type { ValidationIssue } from "./validate.helpers";
import {
  validateTitle, validateBullets, validateCode, validateTerminal,
  validateCompare, validateWalkthrough, validateOutro,
} from "./validate.content";
import { validateDiagram, validateSequence } from "./validate.diagram";
import { validateChart, validateStat } from "./validate.charts";
import type { Video } from "./video";

export type { ValidationIssue } from "./validate.helpers";

const SCENE_KINDS = [
  "title", "bullets", "code", "terminal", "diagram", "sequence",
  "chart", "stat", "compare", "walkthrough", "outro",
] as const;
const VIDEO_THEMES = ["default", "neon", "contrast", "brutal", "stark", "glass", "comic", "metallic"] as const;
const VIDEO_SIZES = ["1080p", "1440p", "4k", "square", "vertical"] as const;
const TRANSITIONS = ["none", "fade", "slide", "wipe"] as const;

function validateMeta(meta: unknown, issues: ValidationIssue[]): void {
  if (meta == null) return;
  if (!isRecord(meta)) { pushError(issues, "meta", "meta must be an object"); return; }
  if (meta.fps != null && ![24, 30, 60].includes(meta.fps as number)) {
    pushError(issues, "meta.fps", "fps must be one of 24, 30, 60");
  }
  optionalEnum(issues, "meta.size", meta.size, "size", VIDEO_SIZES);
  optionalEnum(issues, "meta.theme", meta.theme, "theme", VIDEO_THEMES);
  optionalEnum(issues, "meta.appearance", meta.appearance, "appearance", ["light", "dark"] as const);
  optionalString(issues, "meta.font", meta.font, "font");
  optionalString(issues, "meta.title", meta.title, "title");
  optionalString(issues, "meta.watermark", meta.watermark, "watermark");
  if (meta.progressBar != null && typeof meta.progressBar !== "boolean") pushError(issues, "meta.progressBar", "progressBar must be a boolean");
  if (meta.chapters != null && typeof meta.chapters !== "boolean") pushError(issues, "meta.chapters", "chapters must be a boolean");
}

function validateSceneCommon(scene: Record<string, unknown>, path: string, issues: ValidationIssue[]): void {
  if (scene.pace != null) optionalEnum(issues, `${path}.pace`, scene.pace, "pace", ["slow", "normal", "fast"] as const);
  optionalEnum(issues, `${path}.transition`, scene.transition, "transition", TRANSITIONS);
  optionalString(issues, `${path}.notes`, scene.notes, "notes");
}

/**
 * Validates an `unknown` value against the `Video` schema and returns every
 * problem found — it never throws. `path` is a JSON-ish accessor
 * (`scenes[2].steps[0].flow[1]`) so an author can jump straight to the
 * problem; `severity: "error"` means the scene cannot render correctly,
 * `"warning"` means it renders but reads badly.
 */
export function validateVideo(video: unknown): ValidationIssue[] {
  const issues: ValidationIssue[] = [];
  if (!isRecord(video)) {
    pushError(issues, "", "video must be an object with a \"scenes\" array");
    return issues;
  }

  validateMeta(video.meta, issues);

  if (!Array.isArray(video.scenes) || video.scenes.length === 0) {
    pushError(issues, "scenes", "scenes must be a non-empty array");
    return issues;
  }

  const sceneIds = new Set<string>();
  video.scenes.forEach((scene, i) => {
    const path = `scenes[${i}]`;
    if (!isRecord(scene)) { pushError(issues, path, "scene must be an object"); return; }

    const kind = scene.kind;
    if (!isString(kind) || !(SCENE_KINDS as readonly string[]).includes(kind)) {
      pushError(issues, `${path}.kind`, `unknown scene kind ${JSON.stringify(kind)} — expected one of ${SCENE_KINDS.join(", ")}`);
      return;
    }

    if (scene.id != null) {
      if (!isString(scene.id)) {
        pushError(issues, `${path}.id`, "id must be a string");
      } else if (sceneIds.has(scene.id)) {
        pushError(issues, `${path}.id`, `duplicate scene id "${scene.id}"`);
      } else {
        sceneIds.add(scene.id);
      }
    }

    validateSceneCommon(scene, path, issues);

    switch (kind) {
      case "title": validateTitle(scene, path, issues); break;
      case "bullets": validateBullets(scene, path, issues); break;
      case "code": validateCode(scene, path, issues); break;
      case "terminal": validateTerminal(scene, path, issues); break;
      case "diagram": validateDiagram(scene, path, issues); break;
      case "sequence": validateSequence(scene, path, issues); break;
      case "chart": validateChart(scene, path, issues); break;
      case "stat": validateStat(scene, path, issues); break;
      case "compare": validateCompare(scene, path, issues); break;
      case "walkthrough": validateWalkthrough(scene, path, issues); break;
      case "outro": validateOutro(scene, path, issues); break;
      default: break;
    }
  });

  return issues;
}

/**
 * Validates `video` and throws with every error message listed if any
 * `severity: "error"` issue is found (warnings never throw). On success,
 * returns `video` narrowed to `Video` — the one place in the library that
 * asserts unknown data is safe to hand to `SceneRenderer`/`VideoRoot`.
 */
export function assertVideo(video: unknown): Video {
  const issues = validateVideo(video);
  const errors = issues.filter((i) => i.severity === "error");
  if (errors.length > 0) {
    const lines = errors.map((e) => `  - ${e.path || "(root)"}: ${e.message}`);
    throw new Error(`Invalid Video data (${errors.length} error${errors.length === 1 ? "" : "s"}):\n${lines.join("\n")}`);
  }
  return video as Video;
}
